#!/bin/bash

# SET A GLOBAL VARIABLE TO REPRESENT THE BIN LENGTH ON SOLAR RADII
BIN_LENGTH=0.2

# ANALYSE WHOLE DATA SET AND BIN ACCORDING TO VARIABLE ABOVE
echo "EXECUTING MAIN.PY"
python3 main.py $BIN_LENGTH
echo

# REWRITE EACH BINNED FILE INTO BINNED STATISTICS FILE
echo "EXECUTING BINNED_STATS.PY"
python3 binned_stats.py $BIN_LENGTH
echo

# REITERATE PROCESS, BUT SPLIT BETWEEN APPROACH AND RECESSION (INGRESS AND EGRESS)
echo "EXECUTING APPROACH_RECESSION.PY"
python3 approach_recession.py $BIN_LENGTH
echo

# GENERATE FINAL PLOTS
echo "EXECUTING FINAL_PLOTS.PY"
python3 final_plots.py
echo